### ISSUE TITLE
Round tripping INI-parser?

### ISSUE THREAD

**Issue by VorpalBlade** [CasualX/ini_core#1]
Hi,

I'm in need of a round tripping (i.e. not reformatting on save) INI-parser to be able to semantically patch arbitrary INI-files. This library looks like the closest existing one to my needs for Rust (if I keep the auto trim turned off). However it does have some limitations that I'm wondering if you are interested in addressing / accepting patches from me to address (or if I should just take this project as a basis/inspiration to make my own thing):

* Non-UTF-8: I don't know the encoding of the files I will be working with. Probably UTF-8 almost always, but that is not something I can assume in general. An alternative `[u8]` API would be more suitable for me.
* I don't know the comment symbol in the file in advance (I would like to accept both `#` and `;` at least). Supporting a set of comment symbols would be something I need.
* Support for dealing with "strange" non-standard INI data. Since I'm dealing with arbitrary INI files from arbitrary programs, here are some of the weirdness I have seen and need to do something sensible on:
  * Key & values before the first section
  * "Silly" sections like `[section][subsection][3]` or  `[section[32]]`
  * Weird keys like `AnimationSpeed[$d]` (This one is from a KDE ini file)
* As I said, I need to be able to round trip things without reformatting, so whitespace must be preserved regardless of position. This includes telling `key = value` apart from `key=value` (currently already supported), as well as dealing with trailing whitespaces and blank lines (not sure if this is preserved currently?). From what I can tell, this library with auto-trim turned off is most of the way there, though I have not yet tested it fully.

The reason I need this is that I'm planning on rewriting [this project](https://github.com/VorpalBlade/chezmoi_modify_manager) in Rust (instead of Python) for performance reasons. In that case I had to roll my own ini parser, as Python didn't have what I needed either.

**Comment by CasualX** [comment]
If you're just looking to patch small aspects of an INI file you may be better served by just splitting the file on newlines and applying some simple pattern checks for desired lines to patch.

That said, let's take a look:

* Non-UTF-8: I have no intention to support UTF-16 or anything other than 'ASCII-compatible' encodings. Maybe it is reasonable to make the parser work on `[u8]` instead of `str`. Do know the specific encoding of the files you'd like to parse? You can always try to read the whole file and convert to UTF-8 String before parsing, then emitting the file back by converting back to the target encoding.

* The comment char right now is not optional, but you could set it to `\0` to disable it. Using a manually desugared `for` loop you can inspect the iterator and the remaining contents before it is parsed to dynamically set the comment char eg. if you have a list of characters to support.

  ```rust
  let mut parser = Parser::new("# Comment\n; Comment\n");
  loop {
      if parser.remainder().starts_with("#") {
          parser = parser.comment_char('#');
      }
      else if parser.remainder().starts_with(";") {
          parser = parser.comment_char(';');
      }

      if let Some(item) = parser.next() {
          // ...
      }
      else {
          break;
      }
  }
  ```

* The parser is pretty generous in what it accepts ([docs](https://docs.rs/ini_core/0.2.0/ini_core/#format))
  * Key & values before first section is supported no problem.
  * For sections the line must start with `[` and end with `]`, the rest doesn't matter. If the line starts with `[` but doesn't end with `]` you get an [`Error` item](https://docs.rs/ini_core/0.2.0/ini_core/enum.Item.html#variant.Error).
  * For key/values all that matters is that the line contains a `=`, everything before that is the key, everything after is the value. If `=` is absent the line is still interpreted as a Property, with the value `None`.

* Empty lines are emitted as `Blank` (however if the line contains just whitespace without auto_trim it will return as a Property without a value).

With some effort this library can be used to parse arbitrary ini files, but it was not intended for this use case. I am using to parse very simple config files for my own projects.

There are some ini variants out there that support multiline values, which I have no intention of supporting (but they tend to start with indentation so you can probably wrangle the result into something you want).

**Comment by VorpalBlade** [comment]
Thank you for your quick response! On the whole it seems I would likely benefit from making my own parser (since I need to deal with general data of unknown encoding, i.e. just treat it as opaque byte strings delimited by newlines, equal signs and `[`/`]`.  I still need to parse out the trimmed version but keep the non-trimmed version.

Since I'm not just patching the occasional line but merging two ini-files (system state and git-tracked state) subject to specific rules (e.g. ignore the key where the program store recently opened files), applying a simple pattern is not really a good option.

> There are some ini variants out there that support multiline values, which I have no intention of supporting (but they tend to start with indentation so you can probably wrangle the result into something you want).

Thankfully I have not come across these! I dread the day I would have to deal with them.

I will definitely use this crate as an inspiration and starting point though! I like the overall design of it.

**Comment by CasualX** [comment]
> Thankfully I have not come across these! I dread the day I would have to deal with them.

Since you mentioned python, its [configparser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) does support multiline values :)

> I will definitely use this crate as an inspiration and starting point though! I like the overall design of it.

Go wild, if you want you can use this code as a start and add support for multiple comment chars pretty easy as well as replace all uses of `str` by `[u8]` also pretty easy.

That said these changes are not ones I'd accept for this project.
